### ISSUE TITLE
subgenerators for controller is not rendering.

### ISSUE THREAD

**Issue by apzentral** [srsgores/generator-joomla-component#2]
When you run `yo joomla-component:controller "controller-name"`. It will create somefile.js without any template.
Thanks.

**Comment by srsgores** [comment]
I started looking into it.  Hopefully, I'll have a fix pushed tonight.

**Comment by srsgores** [comment]
Fixed in d936026afe304d90291d2b38fd1e5fb02718225a

**Comment by srsgores** [comment]
@apzentral, you can try updating to `generator-joomla-component@0.0.3` via `npm update generator-joomla-component`.  Let me know if you have any problems.
