### ISSUE TITLE
This doesn't seem to generate a Joomla 3.x Component?

### ISSUE THREAD

**Issue by DC-development** [srsgores/generator-joomla-component#4]
Joomla 3.x Components, according to this article, have a completely different folder structure than this generator would create - I'm a bit puzzled. Maybe I got it all wrong...

https://docs.joomla.org/J3.x:Developing_a_MVC_Component/Developing_a_Basic_Component

**Comment by srsgores** [comment]
Can you elaborate on what you think is missing, or what's not working for you?  I'm not sure I understand your issue/question.

**Comment by DC-development** [comment]
Hi Sean,

I just finished my first component with this tutorial:

https://docs.joomla.org/J3.x:Developing_a_MVC_Component/Developing_a_Basic_Component

Now I wanted to start a "real" one but the file-structure generated is 
nowhere near the one wich is shown there. On the toplevel there should 
be an admin and a site folder for example and I can't find see them 
nowhere in the generated files.

According to the Joomla docs for version 3 it  should look like this:
- /helloworld.xml
  https://docs.joomla.org/J3.x:Developing_a_MVC_Component/Developing_a_Basic_Component#helloworld.xml/
- /site/helloworld.php
  https://docs.joomla.org/J3.x:Developing_a_MVC_Component/Developing_a_Basic_Component#site.2Fhelloworld.php/
- /site/index.html
  https://docs.joomla.org/J3.x:Developing_a_MVC_Component/Developing_a_Basic_Component#index.html/
- /admin/index.html
  https://docs.joomla.org/J3.x:Developing_a_MVC_Component/Developing_a_Basic_Component#index.html/
- /admin/helloworld.php
  https://docs.joomla.org/J3.x:Developing_a_MVC_Component/Developing_a_Basic_Component#admin.2Fhelloworld.php/
- /admin/sql/index.html
  https://docs.joomla.org/J3.x:Developing_a_MVC_Component/Developing_a_Basic_Component#index.html/
- /admin/sql/updates/index.html
  https://docs.joomla.org/J3.x:Developing_a_MVC_Component/Developing_a_Basic_Component#index.html/
- /admin/sql/updates/mysql/index.html
  https://docs.joomla.org/J3.x:Developing_a_MVC_Component/Developing_a_Basic_Component#index.html/
- /admin/sql/updates/mysql/0.0.1.sql
  https://docs.joomla.org/J3.x:Developing_a_MVC_Component/Developing_a_Basic_Component#admin.2Fsql.2Fupdates.2Fmysql.2F0.0.1.sql/

But it doesn't - I don't really get it..../
/

Thx a lot for your quick response!

Best Regards

Phil/
/

**Comment by DC-development** [comment]
I'm sorry bothering  - I just don't seem to understand enough about joomla-component building, yet.

**Comment by srsgores** [comment]
I think you're getting confused about public-facing components and admin components.  This generator generates **admin-facing** components, whereas, when there is a `site` folder, that can contain all public-facing logic.

It might make sense to clarify this in the readme.  Joomla documentation, as in the link you shared, is often conflicting, with different standards/approaches applying to various versions.  This is not something I can fix, and is one of the main pitfalls of using joomla in the first place.  Part of what this component's goal was was to prevent this by imposing certain standards.

What you can do, if you want a public-facing component is **run the generator twice**: once for the admin-facing component, and once for the public-facing component.  You would, of course, remove all the config files, and move them to the top level.

Hope this helps.

**Comment by DC-development** [comment]
Jepp it does, indeed! - very cool - thank you pal!
